version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    networks: 
        - product-network
                
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume

  landoop: 
    image: landoop/fast-data-dev:latest
    container_name: kafka-container
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: "kafka-container"
      KAFKA_ADVERTISED_PORT: "9092"
    networks: 
      - product-network
    ports: 
      - "2181:2181"
      - "3030:3030"      
      - "8081-8083:8081-8083"
      - "9092:9092"
      - "9581-9585:9581-9585"
      
  product: 
    image: product-service
    container_name: product-service
    networks: 
        - product-network
    ports: 
        - '8087:8087'   
    depends_on: 
        - db
        - landoop
        
  input: 
    image: input-service
    container_name: input-service
    networks: 
        - product-network
    ports: 
        - '8086:8086'   
    depends_on: 
        - db
        - landoop    
        
volumes:
  my-db:
networks: 
  product-network:  